### ISSUE TITLE
Powerdown v6 package has incorrect permissions for root folder

### ISSUE THREAD

**Issue by roninkenji** [dlandon/unraid-snap#4]
`root@MediaStore:/# tar tvf /boot/packages/powerdown-2.17-noarch-unRAID.tgz `
`drwxrwxrwx root/root         0 2015-07-25 21:59 ./`
`drwxrwxrwx root/root         0 2015-07-25 21:59 install/`
`-rw-rw-rw- root/root      4693 2015-07-25 21:59 install/doinst.sh`
`..snip...`
`-r-xr-x--- root/root      1567 2015-05-16 11:11 sbin/powerdown`

The permissions for `./` should be 755 (drwxr-xr-x)
This is giving me issues with ssh access :smiley:

**Comment by dlandon** [comment]
Fixed in version 2.18.
