### ISSUE TITLE
ntfs3g unraid v6 driver link 404s

### ISSUE THREAD

**Issue by droidmahn** [dlandon/unraid-snap#6]
The link for the ntfs-3g plugin from slackware 404s
 installplg ntfs-3g-x86_64.plg
plugin: installing: ntfs-3g-x86_64.plg
plugin: downloading: http://slackbuilds.org/mirror/slackware/slackware64-current                                                                 plugin: downloading: http://slackbuilds.org/mirror/slackware/slackware64-current                                                                 /slackware64/a/ntfs-3g-2015.3.14-x86_64-1.txz ... failed (Invalid URL / Server e                                                                 rror response)
plugin: wget: http://slackbuilds.org/mirror/slackware/slackware64-current/slackw                                                                 are64/a/ntfs-3g-2015.3.14-x86_64-1.txz download failure (Invalid URL / Server er                                                                 ror response)

**Comment by dlandon** [comment]
ntfs-3g is built into V6.  I am no longer supporting it.
